- name: Ubuntu provision
  hosts: ubuntu
  become: true
  tasks:
  
    - name: create user
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        password: "{{ item.password | password_hash('sha512') }}"
        shell: "{{ item.shell | default('/bin/bash') }}" 
        state: present
      loop: "{{ user }}"
        
    - name: add ssh keys
      authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ lookup('file', '/home/{{ item.name }}/.ssh/id_rsa.pub') }}"
      loop: "{{ user }}"

    
    - name: install packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: latest
        update_cache: true
    
    - name: copy content to directory
      ansible.builtin.copy:
        src: "/tmp/factory/"
        dest: "{{ root_directory }}"
        remote_src: yes

    - name: Copy nginx default config
      ansible.builtin.template:
        src: "{{ playbook_dir }}/template/default.j2"
        dest: "{{ site_config_dir }}/default"
      notify: reload_nginx
    
  handlers:  
    - name: reload_nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: true
