- name: base_provision
  hosts: ubuntu
  become: true
  ignore_errors: true
  pre_tasks:

    - name: create user
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        password: "{{ item.password | password_hash('sha512') }}"
        shell: /bin/bash
        state: present
      loop: "{{ user }}"
        
    - name: add ssh keys
      authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ lookup('file', '/home/vlad/.ssh/id_rsa.pub') }}"
      loop: "{{ user }}"

  roles:
    - role: node-exporter
    - role: docker
