        
- name: master config
  hosts: master
  become: true
  pre_tasks:

    - name: node preconfig
      ansible.builtin.include_role: 
        name: base-install


# - name: master init
#   hosts: master[0]
#   roles:
#     - role: master-init
#       become: true

#     - role: network-config
#       become_user: "{{ username }}"
#       become: false
      
#     - role: nodelocaldns
#       become_user: "{{ username }}"
#       become: false



