        
- name: master config
  hosts: master
  become: true
  roles:
    - role: node-config
    - role: ha-master
      when: ha_enabled == true


- name: master init
  hosts: master[0]
  roles:
    - role: master-init
      become: true

    - role: network-config
      become_user: "{{ username }}"
      become: false
      
    - role: nodelocaldns
      become_user: "{{ username }}"
      become: false

- name: add another master node
  hosts: master
  become: true
  roles:
    - role: add-master
      when: ha_enabled == true



