- name: node config
  ignore_errors: true
  hosts: master[0]
  tasks:
    
    - name: get token for joinnig pod
      ansible.builtin.shell:
        kubeadm token create --print-join-command
      register: kube_join_token
 
    - name: set fact
      ansible.builtin.set_fact:
        join_command: "{{kube_join_token.stdout}}"
    
    - ansible.builtin.debug:
        var: join_command

- name: config node
  hosts: node
  become: true
  tasks:
    - name: add node
      ansible.builtin.shell: 
         "{{hostvars[groups['master'][0] ].join_command}}"
       

 