---

- name: copy template kubeadm
  ansible.builtin.template:
    src: "{{ kubeadm_temlate }}"
    dest: "/tmp/kubeadm-config.yaml"

- name: kubeadm init
  ansible.builtin.shell: kubeadm init --config /tmp/kubeadm-config.yaml
