- name: base_provision
  hosts: all
  become: true
  ignore_errors: true
  tasks:
    - name: update hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"

    - name: create user
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: "{{ item.groups | | default( item.name ) }}"
        password: "{{ item.password | password_hash('sha512') }}"
        shell: /bin/bash
        state: present
      loop: "{{ user }}"
        

    - name: add ssh keys
      authorized_key:
        user: "{{ item.user }}"
        state: present
        key: "{{ lookup('file', '/home/vlad/.ssh/id_rsa.pub') }}"
      loop: "{{ user }}"

    - name: update file /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{hostvars[item].ansible_fact.ens160.ipv4.address}} {{hostvars[item].ansible_hostname}}"
      loop: "{{groups['all']}}"