
- name: stop Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_dir }}"
    state: absent
  ignore_errors: true

- name: clean prometheus folder
  ansible.builtin.file:
    path: "{{ prometheus_dir }}"
    state: absent
    force: true

- name: create prometheus
  ansible.builtin.include_tasks: prometheus.yaml

- name: create grafana
  ansible.builtin.include_tasks: grafana.yaml
  when: grafana_enabled == true


- name: Generate docker-compose file
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ prometheus_dir }}/docker-compose.yaml"

- name: Start Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_dir }}"
    state: present
    recreate: always

  