groups:
- name: linux alert
  rules:

  - alert: NodeMemoryUsageAbove60%
    expr: 60 > (100 - job:node_memory:available) > 60
    for: 2m
    labels:
      severity: warning
      app_type: linux
      category: memory
    annotations:
      summary: "Node memory usage is going high"
      description: "Node memory for instance {{ $labels.instance }} has reached {{ $value }}%"

  - alert: NodeMemoryUsageAbove75%
    expr: (100 - job:node_memory:available) >= 85
    for: 2m
    labels:
      severity: critical
      app_type: linux
      category: memory
    annotations:
      summary: "Node memory usage is very HIGH"
      description: "Node memory for instance {{ $labels.instance }} has reached {{ $value }}%"

  - alert: NodeCPUUsageHigh
    expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 80
    for: 2m
    labels:
      severity: critical
      app_type: linux
      category: cpu
    annotations:
      summary: "Node CPU usage is HIGH"
      description: "CPU load for instance {{ $labels.instance }} has reached {{ $value }}%"

  - alert: NodeFreeDiskSpaceLess30%
    expr: (sum by (instance) (node_filesystem_free_bytes) / sum by (instance) (node_filesystem_size_bytes)) * 100 < 30
    for: 2m
    labels:
      severity: warning
      app_type: linux
      category: disk
    annotations:
      summary: "Node free disk space is running out"
      description: "Node disk is going to full (< 30% left)  Current free disk space is {{ $value }}"
