Vagrant.configure("2") do |config|
  # General configuration
  config.vm.box = "generic/centos9s"
  #config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.insert_key = false
  # Config VM provider
  config.vm.provider "virtualbox" do |vb|
     vb.memory = 512
     vb.linked_clone = true
       
  end
  # VM provision
 config.vm.provision "ansible" do |ansible|
   ansible.playbook = "base_provision.yaml"
 end
  
  #Config servers
  
  config.vm.define "centos1" do |centos1|
    centos1.vm.hostname = "centos1"
    centos1.vm.network "private_network", ip: "192.168.56.14"
  end
  
 
 

end
