---
- name: get kube-dns ip
  kubernetes.core.k8s:
    api_version: v1
    kind: service
    name: kube-dns
    namespace: kube-system
  register: kube_dns

- name: create localdns
  kubernetes.core.k8s:
    template: "{{ localdns_config }}"
    state: present
