- name: create project {{ grafana_container_name }}
  ansible.builtin.file:
    path: "{{ grafana_dir }}"
    group: "{{ username }}"
    owner: "{{ username }}"
    state: directory

- name: create folder dashboards
  ansible.builtin.file:
    path: "{{ dashboards_folder }}"
    group: "{{ username }}"
    owner: "{{ username }}"
    state: directory

- name: Copy dashboards
  ansible.builtin.copy:
    src: files/dashboards/
    dest: "{{ dashboards_folder }}"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: copy templates for dashboards.yaml to {{ grafana_dir }}
  ansible.builtin.template:
    src: templates/dashboards.yaml.j2
    dest: "{{ grafana_dir }}/dashboards.yaml"
    owner: "{{ username }}"
    group: "{{ username }}"  

- name: copy template datasources.yaml  to {{ grafana_dir }}
  ansible.builtin.template:
    src: templates/datasources.yaml.j2
    dest: "{{ grafana_dir }}/datasources.yaml"
    owner: "{{ username }}"
    group: "{{ username }}"   