- name: Install  collection 
  ansible.builtin.command: "ansible-galaxy collection install -r {{ role_path }}/requirements.yaml --force"
  become: false
  run_once: true
  delegate_to: localhost

- name: Set username
  ansible.builtin.set_fact:
    username: "{{ ansible_user }}"

- name: install victoria metrics
  ansible.builtin.include_tasks: victoriametrics.yaml
  when: victoriametrics_enable == true

- name: install {{ vmalert_container_name }}
  ansible.builtin.include_tasks: "{{ vmalert_container_name }}.yaml"
  when: vmalert_enable == true

- name: install {{ alertmanager_container_name }}
  ansible.builtin.include_tasks: "{{ alertmanager_container_name }}.yaml"
  when: alertmanager_enable == true

- name: install {{ grafanar_container_name }}
  ansible.builtin.include_tasks: "{{ grafana_container_name }}.yaml"
  when: grafana_enable == true

- name: copy docker compose to {{ work_dir }}
  ansible.builtin.template:
    src: templates/docker-compose.yaml.j2
    dest: "{{ docker_compose_dir }}"
    group: "{{ username }}"
    owner: "{{ username }}"

- name: Run monitoring project
  community.docker.docker_compose_v2:
    project_src: "{{ work_dir }}"
    state: present
    build: always

    
    