- name: Check if kubelet.conf exists
  ansible.builtin.stat:
    path: "{{ default_kubelet_conf_file }}"
  register: kubelet_conf

- name: add node to cluster
  ansible.builtin.shell: "{{ token }}"
  when: not kubelet_conf.stat.exists