ENV['VAGRANT_SERVER_URL'] = 'http://vagrant.elab.pro'
Vagrant.configure("2") do |config|
  # General configuration
  config.vm.box = "ubuntu/jammy64"
  #config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.insert_key = false
  # Config VM provider
  config.vm.provider "virtualbox" do |vb|
     vb.memory = 2048
     vb.cpus = 2
     vb.linked_clone = true
       
  end
  
  #Config servers
  #k3s
  config.vm.define "k3s" do |srv1|
    srv1.vm.hostname = "k3s"
    srv1.vm.network "private_network", ip: "192.168.56.20"
  end
end
