# ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'
Vagrant.configure("2") do |config|
    config.vm.box = "generic/rocky9"
    config.ssh.insert_key = false
    config.vm.provider "virtualbox" do |vb|
        vb.name = "k3s"
        vb.cpus = 4
        vb.memory = 2048
        vb.linked_clone = true
    end
    
    
    # VM config
    config.vm.define "rocky" do |rocky|
        rocky.vm.hostname = "k3s"
        rocky.vm.network "private_network", ip: "192.168.57.100"
        rocky.vm.provision "ansible" do |baseprovision|
            baseprovision.limit = "all"
            baseprovision.playbook = "provision/k3s.yaml"
            baseprovision.groups = {
                k3s: ["rocky"]
            }
        end
    end
end