# victoriametrics
victoriametrics_enable: true
scrape_interval: 10s
scrape_file: scrape.yaml
scrape_folder: /etc/prometheus
victoriametrics_data: vmstorage
victoriametrics_image: "{{ victoriametrics_repo }}:{{ victoriametric_version }}"
victoriametrics_command:
- "--storageDataPath=/storage"
- "--retentionPeriod=30d"
- "--promscrape.config={{ scrape_folder }}/scrape.yaml"
victoriametrics_ports:
- "{{ victoriametrics_port }}:{{ victoriametrics_port }}"
victoriametrics_volumes:
- "{{ victoriametrics_data }}:/storage"
- "{{ victoriametrics_dir }}/scrape.yaml:{{ scrape_folder }}/scrape.yaml"

# vmalert config
vmalert_enable: true
rules_folder_on_container: /etc/alerts
rules_folder_on_host: "{{vmalert_dir}}/rules"
vmalert_image: "{{ vmalert_repo }}:{{ vmalert_version }}"
vmalert_command:
- "--remoteRead.url=http://{{ victoriametrics_container_name }}:{{ victoriametrics_port }}"
- "--datasource.url=http://{{ victoriametrics_container_name }}:{{ victoriametrics_port }}"
- "--rule={{ rules_folder_on_container }}/*.yaml"
- "--notifier.url=http://{{alertmanager_container_name }}:{{ alertmanager_port }}"
- "--external.url=http://{{ grafana_container_name }}:{{ grafana_port }}"
vmalert_ports:
- "{{ vmalert_port }}:{{ vmalert_port }}"
vmalert_volumes:
- "{{ rules_folder_on_host }}:{{ rules_folder_on_container }}"

# alertmanager config
alertmanager_enable: true
alertmanager_image: "{{ alertmanager_repo }}:{{ alertmanager_version }}"
alertmanager_command: 
- "--config.file=/etc/alertmanager.yaml"
alertmanager_ports: 
- "{{ alertmanager_port }}:{{ alertmanager_port }}"
alertmanager_volumes:
- "{{ alertmanager_dir }}/alertmanager.yaml:/etc/alertmanager.yaml"

# grafana config
grafana_enable: true
grafana_data: grafana
grafana_datasource_config: "{{ grafana_dir }}/datasources.yaml"
grafana_dashboard_config: "{{ grafana_dir }}/dashboards.yaml"
dashboards_folder: "{{ grafana_dir }}/dashboards"
grafana_dashboard_folder: /var/lib/grafana/dashboard
grafana_image: "{{ grafana_repo }}:{{ grafana_version }}"
grafana_volumes:
- "{{ grafana_data }}:/var/lib/grafana"
- "{{ grafana_datasource_config }}:/etc/grafana/provisioning/datasources/datasources.yaml"
- "{{ grafana_dashboard_config }}:/etc/grafana/provisioning/dashboards/dashboards.yaml"
- "{{ dashboards_folder }}:{{ grafana_dashboard_folder }}"
grafana_ports:
- "{{ grafana_port }}:{{grafana_port}}"

# karma config
karma_enable: true
karma_image: "{{ karma_repo }}:{{ karma_version }}"
karma_command:
- "--alertmanager.uri=http://{{ alertmanager_container_name }}:{{ alertmanager_port }}"
karma_ports:
- "{{ karma_port }}:{{ karma_port }}"

# loki config
loki_enable: true
loki_data: loki_data
loki_image: "{{ loki_repo }}:{{ loki_version }}"
loki_command: 
- "-config.file=/etc/loki/local-config.yaml"
loki_ports:
- "{{ loki_port }}:{{ loki_port }}"
loki_volumes:
- "{{ loki_data }}:/loki"

# Alloy config
alloy_image: "{{ alloy_repo }}:{{ alloy_version }}"
alloy_command:
  - "run"
  - "--server.http.listen-addr=0.0.0.0:{{ alloy_port }}"
  - "/etc/alloy/config.alloy"
alloy_ports:
  - "{{ alloy_port }}:{{ alloy_port }}"
alloy_volumes:
- /var/log:/var/log:ro
- "{{ alloy_dir }}/alloy-config.yaml:/etc/alloy/config.alloy:ro"
