- name: node config
  ignore_errors: true
  hosts: master[0]
  tasks:
    

    - name: get controle-plane certificate
      ansible.builtin.shell:
        kubeadm init phase upload-certs --upload-certs
      register: controle_plane_cert
   
    - name: get token for joinnig pod
      ansible.builtin.shell:
        kubeadm token create --print-join-command
      register: kube_join_token
 
    - name: set fact
      ansible.builtin.set_fact:
        join_master: "{{kube_join_token.stdout_lines[0]}} --control-plane --certificate-key {{ controle_plane_cert.stdout_lines[2]}}"

    - ansible.builtin.debug:
        var: join_master

- name: config ha master
  hosts: master[1-2]
  become: true
  tasks:
   
    - name: add kube-vip 
      ansible.builtin.template:
        src: "{{ kube_vip_template }}"
        dest: /etc/kubernetes/manifests/kube-vip.yaml
   
    
    - name: add master
      shell: 
          "{{hostvars[groups['master'][0] ].join_master}} --apiserver-advertise-address {{ ansible_facts.eth1.ipv4.address }}"
    
    
    - name: create .kube directory
      ansible.builtin.file:
        path: "{{ home_kube_dir }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: create link to conf
      ansible.builtin.file:
        src: "{{ base_kube_conf_dir }}"
        dest: "{{ home_kube_dir }}/config"
        state: link
        owner: "{{ user }}"

   
    