- name: master config
  ignore_errors: true
  hosts: master
  become: false
  tasks:
    - name: script
      ansible.builtin.script:
        "{{playbook_dir}}/calico-metrics.sh"
     
                
                
