- name: master config
  ignore_errors: true
  hosts: master
  become: true
  tasks:
    - name: update file /etc/hosts
      ansible.builtin.debug:
        var: ansible_facts

      # loop: "{{groups.all}}"