- name: master config
  ignore_errors: true
  hosts: master
  become: false
  tasks:
    - name: script
      ansible.builtin.debug:
        var: ansible_facts.hostname
     
                
                
