Vagrant.configure("2") do |config|
    config.vm.box = "generic/rocky8"
    config.ssh.insert_key = false
    
    
    config.vm.provision "ansible" do |ansible|
        ansible.limit = "all"
        ansible.playbook = "./base_provision.yaml"
        

    end    
    Node = 3
    Master = 1
    
    # VM config node
    (1..Node).each do |node_id|
        config.vm.define "node#{node_id}" do |node|
           node.vm.hostname = "node#{node_id}"
           node.vm.network "private_network", ip: "192.168.59.#{10+node_id}"
           node.vm.provider "virtualbox" do |vb|
             vb.memory = 1024
             vb.linked_clone = true
             vb.cpus = 2
           end
        end
    end
    (1..Master).each do |master_id|
        config.vm.define  "master#{master_id}" do |master|
          master.vm.hostname = "master#{master_id}"
          master.vm.network "private_network", ip: "192.168.59.#{20+master_id}"
          master.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 2
            vb.linked_clone = true
          end
        end
    end    
end