Vagrant.configure("2") do |config|
  # General configuration
  config.vm.box = "generic/ubuntu2010"
  #config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.insert_key = false
  # Config VM provider
  config.vm.provider "virtualbox" do |vb|
     vb.memory = 2048
     vb.linked_clone = true
       
  end
  # VM provision
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "base_provision.yaml"
  end
  
  #Config servers
  #ubuntu
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.hostname = "ubuntu"
    ubuntu.vm.network "private_network", ip: "192.168.56.2"
  end

 

end
