- name: base_provision
  hosts: all
  become: true
  ignore_errors: true
  tasks:
    - name: update hostname
      ansible.builtin.hostname:
        name: "{{ new_hostname }}"

    - name: create user
      ansible.builtin.user:
        name: "{{ user }}"
        groups: wheel
        password: "{{ password | password_hash('sha512') }}"
        shell: /bin/bash
        state: present
        

    - name: add ssh keys
      authorized_key:
        user: "{{ user }}"
        state: present
        key: "{{ lookup('file', '/home/vlad/.ssh/id_rsa.pub') }}"

