Vagrant.configure("2") do |config|
  # General configuration
  config.vm.box = "generic/rocky8"
  #config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.insert_key = false
  # Config VM provider
  config.vm.provider "virtualbox" do |vb|
     vb.memory = 512
     vb.linked_clone = true
       
  end
  # VM provision
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "base_provision.yaml"
  end
  
  #Config servers
  
  config.vm.define "rocky1" do |rocky1|
    rocky1.vm.hostname = "rocky1"
    rocky1.vm.network "private_network", ip: "192.168.56.12"
  end
  
  config.vm.define "rocky2" do |rocky2|
    rocky2.vm.hostname = "rocky2"
    rocky2.vm.network "private_network", ip: "192.168.56.13"
  end
 

end
