# ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'
Vagrant.configure("2") do |config|
   config.vm.box = "generic/rocky9"
   config.ssh.insert_key = false
   #  config.vm.provider "virtualbox" do |vb|
   #      vb.memory = 512
   #      vb.linked_clone = true
   #  end
   config.vm.provider "vmware_desktop" do |v|
      v.gui = true
      v.linked_clone = false
      v.vmx["memsize"] = "1024"
      v.vmx["numvcpus"] = "1"
   end
   N = 1
    
    # VM config
    (1..N).each do |i|
        config.vm.define "srv#{i}" do |srv|
           srv.vm.hostname = "rocky#{i}"
           srv.vm.network "private_network", ip: "192.168.59.#{1+i}"
           if i == N
              srv.vm.provision "ansible" do |baseprovision|
                 baseprovision.limit = "all"
                 baseprovision.playbook = "provision/base_provision.yaml"
                 baseprovision.groups = {
                    rocky: ["srv[1:#{N}]"]
                 }
              end
           end
        end
    end
end
