---
- name: config node
  hosts: node
  
  become: false
  tasks:
    - ansible.builtin.template:
        src: "{{ playbook_dir }}/haproxy.j2"
        dest: ~/haproxy.conf
  

      
      
      
        

      