---
- name: config node
  hosts: master
  
  become: false
  tasks:
    - name: Get an existing Pods in the kubernetes cluster
      ansible.builtin.shell:
        kubectl get namespace calico-system
        
      register: service

    - ansible.builtin.debug:
        var: service
     