---
- name: config node
  hosts: node
  
  become: true
  tasks:
    

    - name: copy config
      ansible.builtin.copy:
        src: /home/{{ name }}/.kube/config
        dest: "{{home_kube_dir}}"
      delegate_to: master