Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2010"
    config.ssh.insert_key = false
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 512
        vb.linked_clone = true
    end
    N = 3
    
    # VM config
    (1..N).each do |i|
        config.vm.define "srv#{i}" do |srv|
           srv.vm.hostname = "rocky#{i}"
           srv.vm.network "private_network", ip: "192.168.59.#{10+i}"
           if i == N
              srv.vm.provision "ansible" do |baseprovision|
                 baseprovision.limit = "all"
                 baseprovision.playbook = "./provision/base_provision.yaml"
                 baseprovision.inventory_path = "inventory"
              end
           end
        end
    end
end