ENV["VAGRANT_EXPERIMENTAL"] = "disks"
Node = 2
Master = 1


Vagrant.configure("2") do |config|
    config.vm.box = "generic/rocky9"
    config.ssh.insert_key = false
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.linked_clone = true
      vb.cpus = 2
    end

    (1..Master).each do |master_id|
      config.vm.define  "master#{master_id}" do |master|
        master.vm.hostname = "master#{master_id}"
        master.vm.network "private_network", ip: "192.168.1.#{10+master_id}"
        if master_id == Master
          master.vm.provision "ansible" do |master_ansible|
            master_ansible.limit = "all"
            master_ansible.playbook = "provision/master-playbook.yaml"
            master_ansible.groups = {
              "master" => ["master[1:#{Master}]"],
              "node" => ["node[1:#{Node}]"]
            }
          end
        end
      end
    end    

    # VM config node
    (1..Node).each do |node_id|
        config.vm.define "node#{node_id}" do |node|
            node.vm.hostname = "node#{node_id}"
            node.vm.network "private_network", ip: "192.168.1.#{20+node_id}"
            node.vm.disk :disk, size: "10GB", name: "data" 
            node.vm.disk :disk, size: "10GB", name: "ssd" 
            if node_id == Node
              node.vm.provision "ansible" do |node_ansible|
                node_ansible.limit = "all"
                node_ansible.playbook = "provision/node-playbook.yaml"
                node_ansible.groups = {
                  "master" => ["master[1:#{Master}]"],
                  "node" => ["node[1:#{Node}]"]
                }
              end
            end
        end
    end    
end