- name: get token from master1
  ansible.builtin.shell: kubeadm token create --print-join-command
  register: master_join_token
  # delegate_to: "{{ groups['master'][0] }}"

- name: set token fact
  ansible.builtin.set_fact:
    master_token: "{{ master_join_token.stdout }}"

- name: get certificate
  ansible.builtin.shell: kubeadm init phase upload-certs --upload-certs | tail -1
  register: certificate
  # delegate_to: "{{ groups['master'][0] }}"

- name: set token fact
  ansible.builtin.set_fact:
    certificate: "{{ certificate.stdout }}"

