Vagrant.configure("2") do |config|
    # General configuration
    config.vm.box = "generic/rocky9"
    #config.vm.synced_folder ".", "/vagrant", disabled: true
    config.ssh.insert_key = false
    # Config VM provider
    config.vm.provider "virtualbox" do |vb|
       vb.memory = 512
       vb.cpus = 2
       vb.linked_clone = true
       
         
    end
    
    #Config servers
    config.vm.define "rocky" do |rocky|
      rocky.vm.hostname = "nfs"
      rocky.vm.network "private_network", ip: "192.168.59.100"
    end

    # VM provision
    config.vm.provision "ansible" do |ansible|
        ansible.limit = "all"
        ansible.playbook = "provision/install.yaml"
        ansible.groups = {
          nfs: ['rocky']
         }
    end
end
  
   
