---
- name: update hosts
  hosts: all
  become: true
  tasks: 
    - name: update file /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{hostvars[item].ansible_facts.eth1.ipv4.address}} {{hostvars[item].ansible_hostname}}"
      loop: "{{groups['all']}}"

    #  - ansible.builtin.debug:
    #     var: ansible_facts.eth1.ipv4.address
      