ENV["VAGRANT_EXPERIMENTAL"] = "disks"
N = 1

Vagrant.configure("2") do |config|
  # General configuration
  config.vm.box = "generic/rocky9"
  #config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.insert_key = false
  # Config VM provider
  config.vm.provider "virtualbox" do |vb|
     vb.memory = 512
     vb.linked_clone = true
     vb.cpus = 1
  # vb.name = "srv-#{i}"
  end
  
  #Config servers
  (1..N).each do |i|
    config.vm.define "srv#{i}" do |srv|
      srv.vm.hostname = "srv-#{i}"
      srv.vm.network "private_network", ip: "192.168.57.1#{i}"
      srv.vm.disk :disk, size: "10GB", name: "data"
      if i == N
        srv.vm.provision "ansible" do |ansible|
          ansible.limit = "all"
          ansible.playbook = "provision/base_provision.yaml"
          ansible.groups = {
            srv: ["srv[1:#{i}]"]
          }
        end
      end
    end
  end
end
