Vagrant.configure("2") do |config|
  # General configuration
  config.vm.box = "generic/ubuntu2010"
  #config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.insert_key = false
  # Config VM provider
  config.vm.provider "virtualbox" do |vb|
     vb.memory = 512
     vb.linked_clone = true
     vb.cpus = 1
  end
  # VM provision
  config.vm.provision "ansible" do |ansible|
   ansible.playbook = "playbook.yaml"
  end
  
  #Config servers
  
  #srv1
  config.vm.define "srv1" do |srv1|
    srv1.vm.hostname = "srv1"
    srv1.vm.network "private_network", ip: "192.168.56.10"
  end
  #srv2
  config.vm.define "srv2" do |srv2|
    srv2.vm.hostname = "srv2"
    srv2.vm.network "private_network", ip: "192.168.56.11"
  end
end
