ENV['VAGRANT_SERVER_URL'] = 'http://vagrant.elab.pro'
Vagrant.configure("2") do |config|
  # General configuration
  config.vm.box = "ubuntu/jammy64"
  #config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.insert_key = false
  # Config VM provider
  config.vm.provider "virtualbox" do |vb|
     vb.memory = 512
     vb.linked_clone = true
     vb.cpus = 1
  end
  
  #Config servers
  (1..2).each do |i|
    config.vm.define "srv#{i}" do |srv|
      srv.vm.hostname = "srv#{i}"
      srv.vm.network "private_network", ip: "192.168.56.10#{i}", bridge: "enp0s8"
    end
  end
  
   
  # Provission
  config.vm.provision "ansible" do |ansible|
   ansible.limit = "all"
   ansible.playbook = "base_provision.yaml"
   ansible.groups = {
    srv: ['srv1', 'srv2'],
   }
  end
  
end
