url: https://download.docker.com/linux/{{ ansible_facts.distribution | lower }}/gpg
repo:  deb https://download.docker.com/linux/{{ ansible_facts.distribution | lower }} {{ ansible_facts.distribution_release }} stable
