---
- name: use var for ubuntu
  ansible.builtin.include_vars: rhel

- name: get service facts
  ansible.builtin.service_facts:


- name: install docker
  block:

  - name: Add Docker repository
    ansible.builtin.get_url:
      url: "{{ repo_url }}"
      dest: "{{ repo_dest }}"

  - name: install packages
    ansible.builtin.dnf:
      name: "{{ packages }}"
      state: present
      update_cache: true
    notify: started_docker

  - name: add user to docker group
    ansible.builtin.user:
      user: "{{ username }}"
      group: docker
      append: true

  - name: Create a network
    docker_network:
      name: "{{ docker_network_name }}"

  when: service_name not in ansible_facts.services
