---
# install docker on ubuntu
- name: add gpg key
  ansible.builtin.apt_key:
    url: "{{ url }}"
    state: present
    validate_certs: no

- name: add repo
  ansible.builtin.apt_repository:
    repo:  "{{ repo }}"
    state: present
          
- name: install docker soft
  ansible.builtin.apt:
    name: "{{ docker_soft }}"
    state: present
    update_cache: true
  notify: service started

- name: edit cgrops by systemd
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/system/docker.service
    regexp: '^ExecStart'
    line: 'ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --exec-opt native.cgroupdriver=systemd'
    backrefs: yes
  
- name: config reload
  ansible.builtin.systemd:
    daemon_reload: true
  
 

  