---
# tasks file for docker_install

- name: include OS vars
  include_vars: "{{ ansible_facts.distribution}}.yaml"

- name: install docker on ubuntu
  ansible.builtin.include_tasks: docker_ubuntu.yaml
  when: ansible_facts.distribution == "Ubuntu"
    
- name: modify usergroup
  ansible.builtin.user:
    name: "{{ name }}"
    groups: "{{ docker_group }}"
    append: true
  


   
 
   


        

      