- name: get token from master
  ansible.builtin.shell: kubeadm token create  --print-join-command
  register: master_join_token
  delegate_to: "{{ groups['master'][0] }}"

- name: get certificate
  ansible.builtin.shell: kubeadm init phase upload-certs --upload-certs | tail -1
  register: certificate
  delegate_to: "{{ groups['master'][0] }}"

- name: set join facts
  ansible.builtin.set_fact:
    certificate: "{{ certificate.stdout }}"
    master_token: "{{ master_join_token.stdout }}"
