monitoring_enable: true 

# Default Dirs
docker_compose_dir: "{{ work_dir }}/docker-compose.yaml"
work_dir: "/home/{{ username }}/monitoring"
victoriametrics_dir: "{{ work_dir }}/{{ victoriametrics_container_name }}"
vmalert_dir: "{{ work_dir }}/{{ vmalert_container_name }}"
alertmanager_dir: "{{ work_dir }}/{{ alertmanager_container_name }}"
grafana_dir: "{{ work_dir }}/{{ grafana_container_name }}"
karma_dir: "{{ work_dir }}/{{ karma_container_name }}"
loki_dir: "{{ work_dir }}/{{ loki_container_name }}"
alloy_dir: "{{ work_dir }}/{{ alloy_container_name }}"
default_metrics_path: metrics

# network config
monitoring_network: monitoring_network

# Default container name
victoriametrics_container_name: victoriametrics
vmalert_container_name: vmalert
alertmanager_container_name: alertmanager
grafana_container_name: grafana
karma_container_name: karma
loki_container_name: loki
alloy_container_name: alloy

# Default repo
vmalert_repo: victoriametrics/vmalert
victoriametrics_repo: victoriametrics/victoria-metrics
alertmanager_repo:  prom/alertmanager
grafana_repo:  grafana/grafana
karma_repo: ghcr.io/prymitive/karma
loki_repo: grafana/loki
alloy_repo: grafana/alloy

# Default version
victoriametric_version: v1.118.0
alertmanager_version: v0.28.0
grafana_version: 11.5.0
karma_version: v0.121
vmalert_version: v1.118.0
loki_version: 3.5.1
alloy_version: latest

# Default port
victoriametrics_port: 8428
vmalert_port: 8880
alertmanager_port: 9093
grafana_port: 3000
karma_port: 8080
loki_port: 3100
alloy_port: 12345


