---
- name: get service facts
  ansible.builtin.service_facts:


- name: install node-exporter
  ansible.builtin.include_tasks: node-exporter.yaml
  when:  '"{{ exporter_service_name }}" not in ansible_facts.services or ansible_facts.services["{{exporter_service_name}}"].state != "running"' 
