# #User data
username: vlad
password: '8231'

#Repo data
kubernetes_repo: https://pkgs.k8s.io/core:/stable:/v1.31/rpm/
kubernetes_gpg_key: https://pkgs.k8s.io/core:/stable:/v1.31/rpm/repodata/repomd.xml.key

#Req soft

soft_for_install:
- wget
- nano
- curl
- iproute-tc
- vim
- git
- bash-completion
- nfs-utils
- python3
- containerd.io
- kubectl.x86_64
- kubelet.x86_64
- kubeadm.x86_64
- ipvsadm
- python3-pip
- sysstat
- jq
- net-tools
- tree
- traceroute
- iscsi-initiator-utils
- nfs-utils
- nfs4-acl-tools


# - cri-o
#Req modules
modules:
- overlay
- br_netfilter
- nf_nat
- xt_REDIRECT
- xt_owner
- iptable_nat
- iptable_mangle
- iptable_filter
- iscsi_tcp

#sysctl param
sysctl_param:
- net.bridge.bridge-nf-call-ip6tables
- net.bridge.bridge-nf-call-iptables
- net.ipv4.ip_forward

#Req pip module
pip_modules:
- kubernetes

#Kube config file
kubernetesVersion: 'v1.31.0'
base_kube_conf_dir: /etc/kubernetes/admin.conf
kubeadm_temlate: "{{playbook_dir}}/template/kubeadm-config.j2"
# kubeadm_config: /tmp/kubeadm-config.yaml
localdns_config: "{{playbook_dir}}/template/localdns.j2"
home_kube_dir: /home/vagrant/.kube

#Net config
# node_ip: 192.168.56.24
podSubnet: 10.244.0.0/16
serviceSubnet: 10.243.0.0/16
network_operator: https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/tigera-operator.yaml
calico: "{{playbook_dir}}/template/kube-calico-cdr.j2"
calico_enable_metrics: "{{playbook_dir}}/files/calico-enable-metric.sh" 