 #User data
# username: vlad
# password: '8231'

#Repo data
kubernetes_repo: https://pkgs.k8s.io/core:/stable:/v1.30/rpm/
kubernetes_gpg_key: https://pkgs.k8s.io/core:/stable:/v1.30/rpm/repodata/repomd.xml.key

#Req soft

soft_for_install:
- wget
- nano
- curl
- iproute-tc
- vim
- git
- bash-completion
- nfs-utils
- python3
- containerd.io
- kubectl.x86_64
- kubelet.x86_64
- kubeadm.x86_64
- ipvsadm
- python3-pip
- sysstat
- jq
- net-tools
- tree
- traceroute


# - cri-o
#Req modules
modules:
- overlay
- br_netfilter
- nf_nat
- xt_REDIRECT
- xt_owner
- iptable_nat
- iptable_mangle
- iptable_filter

#sysctl param
sysctl_param:
- net.bridge.bridge-nf-call-ip6tables
- net.bridge.bridge-nf-call-iptables
- net.ipv4.ip_forward

#Req pip module
pip_modules:
- kubernetes

#Kube config file
kubernetesVersion: 'v1.30.1'

# Add node in cluster
node_in_cluster: hostvars[groups['master'] ].node_exist.stdout_lines

  