- name: base_provision
  hosts: all
  become: true
  tasks:
  
    - name: create user
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        password: "{{ item.password | password_hash('sha512') }}"
        shell: "{{ item.shell | default('/bin/bash') }}" 
        state: present
      loop: "{{ user }}"
        
    - name: add ssh keys
      authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ lookup('file', '/home/{{ item.name }}/.ssh/id_rsa.pub') }}"
      loop: "{{ user }}"

    - name: update file /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{hostvars[item].ansible_facts.eth1.ipv4.address}} {{hostvars[item].ansible_hostname}}"
      loop: "{{groups['all']}}"

    - name: add gpg key
      ansible.builtin.apt_key:
        url: "{{ item }}"
        state: present
        validate_certs: no
      loop: "{{ gpg_keys }}"

    - name: add repo
      ansible.builtin.apt_repository:
        repo:  "{{ item }}"
        state: present
      loop: "{{ repo }}"
    
    - name: update package
      ansible.builtin.apt:
        name: '*'
        state: latest
        update_cache: true

    - name: install base soft
      ansible.builtin.apt:
        name: "{{ soft }}"
        state: present
        update_cache: true

    - name: modify usergroup
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        state:  present
      loop: "{{ user }}"
        
    - name: Change /var/run/docker.sock permission
      ansible.builtin.file:
        path: /var/run/docker.sock
        mode: '0666'
           
        
        
        
          
