- name: base_provision
  hosts: all
  become: true
  tasks:

  - name: create user
    ansible.builtin.user:
      name: "{{ username }}"
      groups: sudo
      password: "{{ password | password_hash('sha512') }}"
      shell: /bin/bash'
      state: present

  - name: add ssh keys
    authorized_key:
      user: "{{ username }}"
      state: present
      key: "{{ lookup('file', '/home/vlad/.ssh/id_rsa.pub') }}"

  - name: update file /etc/hosts
    ansible.builtin.lineinfile:
      path: /etc/hosts
      line: "{{hostvars[item].ansible_facts.eth1.ipv4.address}} {{hostvars[item].ansible_hostname}}"
    loop: "{{groups['all']}}"

  - name: install base soft
    ansible.builtin.apt:
      name: "{{ soft }}"
      state: present
      update_cache: true

  
  - name: install docker
    ansible.builtin.include_role:
      name: docker 


  - name: install monitoring
    vars:
      alertmanager_enable: true
      victoriametrics_enable: true
      vmalert_enable: true
    ansible.builtin.include_role:
      name: monitoring


