---

- name: disable firewall
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: false

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled

- name: load module
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ modules }}"

- name: make module persistent
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/modules.conf
    line: "{{ item }}"
    create: yes
  loop: "{{ modules }}"

- name: set "{{ item.key }}" to "{{ item.value}}"
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    state: present
    value: "{{ item.value}}"
    reload: true
  loop: "{{ sysctl_params }}"

- name: disable swap
  ansible.builtin.shell: swapoff -a

- name: remove swaw from fstab
  ansible.builtin.lineinfile:
    dest: /etc/fstab
    regexp: swap
    state: absent

- name: update config containerd
  ansible.builtin.shell: |
    containerd config default | sudo tee /etc/containerd/config.toml
    sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
    grep -A1 -lZR registry] /etc/containerd/config.toml | xargs -0 -l  sed  -i 's/config_path \= ""/config_path = "\/etc\/containerd\/certs.d"/g'
  notify:
  - restart containerd

- name: start handler force
  meta: flush_handlers

- name: bashrc edit
  ansible.builtin.blockinfile:
    dest: /home/{{ username }}/.bashrc
    block: |
      source <(kubectl completion bash)
      alias k=kubectl
      complete -o default -F __start_kubectl k
