- name: install haproxy and keeplived
  ansible.builtin.yum:
    name: "{{ ha_packages }}"
    state: present
    update_cache: true

- name: create config haproxy
  ansible.builtin.template:
    src: "{{ haproxy_config_tempate }}"
    dest: "{{ haproxy_config_dir }}"
    mode: '0600'
  notify: restart_haproxy

- name: create config keepalived
  ansible.builtin.template:
    src: "{{ keepalived_config_template }}"
    dest: "{{ keepalived_config_dir }}"
    mode: '0600'
  notify: restart_keepalived

  