---
# Base provision for node, create user, add ssh key ant etc
- name: node-baseprovision
  ansible.builtin.include_tasks: tasks/baseprovision.yaml

# Install base soft
- name: install-base-packages
  ansible.builtin.include_tasks: tasks/install-base-packages.yaml

- name: install calicoctl on master
  ansible.builtin.include_tasks: tasks/install-calicoctl.yaml 
  when: inventory_hostname in groups['master']
# Config node
- name: node-config
  ansible.builtin.include_tasks: tasks/config-nodes.yaml


# Install and config haproxy and keeplived
