---
- name: get list node and get token
  ansible.builtin.include_tasks: prepare_master.yaml
  when: inventory_hostname == groups['master'][0]

- name: join node
  ansible.builtin.include_tasks: join_node.yaml
  when: inventory_hostname == groups['node']
  
    
# - name: get list nodes
#   ansible.builtin.shell: kubectl get node -o json | jq '.items[].metadata.name'
#   register: node_list

# - name: set fact
#   ansible.builtin.set_fact:
#     node_list: "{{ node_list.stdout_lines | join(',') }}"

# - name: get token for joinnig pod
#   ansible.builtin.shell:
#     kubeadm token create --print-join-command
#   register: kube_join_token

# - name: set fact
#   ansible.builtin.set_fact:
#     join_command: "{{kube_join_token.stdout}}"