- name: get list nodes
  ansible.builtin.shell: kubectl get node -o json | jq '.items[].metadata.name'
  register: node_list

- name: set fact
  ansible.builtin.set_fact:
    node_list: "{{ node_list.stdout_lines | join(',') }}"

- name: get token for joinnig pod
  ansible.builtin.shell:
    kubeadm token create --print-join-command
  register: node_join_token