- name: base_provision
  hosts: all
  become: true
  tasks:
    - name: update hostname
      ansible.builtin.hostname:
        name: "{{ new_hostname }}"
  
    - name: create user
      ansible.builtin.user:
        name: "{{ name }}"
        groups: sudo
        password: "{{ password | password_hash('sha512') }}"
        shell: "{{ shell | default('/bin/bash') }}" 
        state: present
        

    - name: add ssh keys
      authorized_key:
        user: "{{ name }}"
        state: present
        key: "{{ lookup('file', '/home/{{ name }}/.ssh/id_rsa.pub') }}"

   