- name: base_provision
  hosts: all
  become: true
  vars:
    name: vlad
    password: '8231'
  tasks:
    - name: set timezone
      community.general.timezone:
        name: Europe/Moscow
      
    - name: create user
      ansible.builtin.user:
        name: "{{ name }}"
        groups: sudo
        password: "{{ password | password_hash('sha512') }}"
        shell: "{{ shell | default('/bin/bash') }}" 
        state: present
        

    - name: add ssh keys
      authorized_key:
        user: "{{ name }}"
        state: present
        key: "{{ lookup('file', '/home/{{ name }}/.ssh/id_rsa.pub') }}"

    - name: update file /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{hostvars[item].ansible_facts.eth1.ipv4.address}} {{hostvars[item].ansible_hostname}}"
      loop: "{{groups['all']}}"


   