---
- name: install dependence
  hosts: all
  become: true
  vars:
    soft:
      - curl
      - ca-certificates
      - apt-transport-https
  tasks:
    - name: install req software
      ansible.builtin.apt:
        name: "{{ soft }}"
        state: present
        update_cache: true

    - name: install docker
      ansible.builtin.include_role:
        name: docker_install
        
    - name: disable swap 
      ansible.builtin.shell:
        swapoff -a

    - name: remove swaw from fstab
      ansible.builtin.lineinfile:
        dest: /etc/fstab
        regexp: swap
        state: absent
    
    
  tags: install dependences
      
- name: install kubeadm, kubelet on all node
  hosts: all
  become: true
  vars:
    kube_soft_all:
       - kubelet=1.20.1-00
       - kubeadm=1.20.1-00
  tasks:
    - name: add k8s apt key
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
        
    - name: add k8s repo
      ansible.builtin.apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: 'kubernetes'
    
    - name: install soft
      ansible.builtin.apt:
        name: "{{ kube_soft_all }}"
        state: present
        update_cache: true
    
    - name: start and enable service kubelet
      ansible.builtin.service:
        name: kubelet
        state: started
        enabled: true
  tags: kube_all_install

- name: install kubectl on master node
  hosts: master
  become: true
  vars:
    soft_for_master: kubectl
  tasks:
    - name: install kubectl=1.20.1-00
      ansible.builtin.apt:
        name: "{{ soft_for_master }}"
        state: present
  tags: kube_master_install
  
- name: install cluster
  ignore_errors: true
  hosts: master
  tasks:
    - name: check if cluster are running
      ansible.builtin.shell:
        ps -aux | grep kube-api | grep -v grep
      register: isrunning
      ignore_errors: true

    - name: cluster init
      ansible.builtin.shell:
        kubeadm init --apiserver-advertise-address=192.168.59.12 --pod-network-cidr=10.244.0.0/16
      when: isrunning.rc != 0
  tags: install_cluster
      
- name: config cluster
  ignore_errors: true
  hosts: master
  tasks:
    - name: create .kube directory
      ansible.builtin.file:
        path: /home/vlad/.kube
        state: directory
        mode: 0755

    - name: copy conf to .kube directory
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vlad/.kube/config
        remote_src: true
        owner: vlad

    - name: check if pod network exist
      become: false
      ansible.builtin.shell:
        kubectl get pod --all-namespaces
      register: network_exist

    - name: install pod network
      become: false
      ansible.builtin.shell:
         kubectl apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml
  tags: config_cluster

- name: get token
  ignore_errors: true
  hosts: master
  tasks:
    - name: get token for joinnig pod
      ansible.builtin.shell:
        kubeadm token create --print-join-command
      register: kube_join_token
 
    - name: set fact
      ansible.builtin.set_fact:
        join_command: "{{kube_join_token.stdout_lines[0]}}"

- name: config node
  hosts: node
  become: true
  tasks:
    - ansible.builtin.shell:
        "{{hostvars['192.168.59.12']['join_command']}}"
      
  tags: config_node
          
         
      