- name: master config
  hosts: master
  become: true

  roles:
    - role: common-config
    
    - role: ha-master-config
      when: ha_enabled == true
    
    - role: master-config
      when: inventory_hostname == groups['master'][0]

    - role: master-add
      when: ha_enabled == true
