- name: node config
  ignore_errors: true
  hosts: master
  tasks:
    - name: get controle-plane certificate
      ansible.builtin.shell:
        kubeadm init phase upload-certs --upload-certs
      register: controle_plane_cert
   
    - ansible.builtin.debug:
        var: controle_plane_cert.stdout_lines[2]

    - name: get token for joinnig pod
      ansible.builtin.shell:
        kubeadm token create --print-join-command
      register: kube_join_token
 
    - name: set fact
      ansible.builtin.set_fact:
        join_command: "{{kube_join_token.stdout_lines[0]}} --control-plane --certificate-key {{ controle_plane_cert.stdout_lines[2]}}"

    - ansible.builtin.debug:
        var: join_command

- name: config ha master
  hosts: master-ha
  become: true
  tasks:
   
    - name: add kube-vip 
      ansible.builtin.template:
        src: "{{ kube_vip_template }}"
        dest: /etc/kubernetes/manifests/kube-vip.yaml
   
    - name: add ha master
      ansible.builtin.shell: "{{hostvars[groups['master'] | join(',')]['join_command']}}"

    - name: create .kube directory
      ansible.builtin.file:
        path: "{{ home_kube_dir }}"
        state: directory
        owner: "{{ name }}"
        group: "{{ name }}"

    - name: copy conf to .kube directory
      ansible.builtin.copy:
        src:  /etc/kubernetes/admin.conf
        dest: /home/{{ name }}/.kube/config
        remote_src: true
        owner: "{{ name }}"
        group: "{{ name }}"