- name: config master
  ignore_errors: true
  hosts: master
  tasks:
    - name: import k8s images
      ansible.builtin.shell:
        kubeadm config images pull

    - name: check if cluster are running
      ansible.builtin.shell:
        ps -aux | grep kube-api | grep -v grep
      register: isrunning
      ignore_errors: true

    - name: init cluster
      block:
       - name: copy template kubeadm
         ansible.builtin.template:
          src: "{{ kubeadm_temlate }}"
          dest: "{{ kubeadm_config }}"
        
       - name: kubeadm init
         ansible.builtin.shell:
           kubeadm init --config "{{ kubeadm_config }}"
      when: isrunning.rc != 0

    - name: create .kube directory
      ansible.builtin.file:
        path: "{{ home_kube_dir }}"
        state: directory
        owner: "{{ name }}"
        group: "{{ name }}"

    - name: copy conf to .kube directory
      ansible.builtin.copy:
        src: "{{ base_kube_conf_dir }}"
        dest: /home/{{ name }}/.kube/config
        remote_src: true
        owner: "{{ name }}"
        group: "{{ name }}"
    
      
    - name: copy template for calico network
      ansible.builtin.template:
        src: "{{ custom_resource_temlate_dir }}"
        dest: "{{ custom_resource_dir }}"

    - name: check if pod network exist
      become: false
      ansible.builtin.shell: kubectl get namespaces calico-system
      register: network_exist

    - name: install calico 
      block:
        - name: install network operator
          ansible.builtin.shell:
            kubectl create -f "{{ network_operator }}"
          
        - name: install custom resource 
          ansible.builtin.shell:
            kubectl create -f "{{ custom_resource_dir }}"
      become: false
      when: network_exist.rc != 0



        
        
    
      
    