- name: node config
  ignore_errors: true
  hosts: master
  tasks:
    - name: get token for joinnig pod
      ansible.builtin.shell:
        kubeadm token create --print-join-command
      register: kube_join_token
 
    - name: set fact
      ansible.builtin.set_fact:
        join_command: "{{kube_join_token.stdout_lines[0]}}"

- name: config node
  hosts: node
  become: true
  tasks:
    - ansible.builtin.shell:
        "{{hostvars[groups['master'] | join(',')]['join_command']}}"
      
  