- name: node config
  ignore_errors: true
  hosts: master
  tasks:
    
    - name: get token for joinnig pod
      ansible.builtin.shell:
        kubeadm token create --print-join-command
      register: kube_join_token
 
    - name: set fact
      ansible.builtin.set_fact:
        join_command: "{{kube_join_token.stdout_lines[0]}}"

    - ansible.builtin.debug:
        var: join_command

- name: config node
  hosts: node
  become: true
  tasks:
    - name: add node 
      ansible.builtin.shell: "{{ node_add }}"