- name: copy template kubeadm
  ansible.builtin.template:
    src: "kubeadm-config.j2"
    dest: "/tmp/kubeadm-config.yaml"

- name: kubeadm init
  ansible.builtin.shell: kubeadm init --config /tmp/kubeadm-config.yaml

- name: create `.kube` directory
  ansible.builtin.file:
    path: "{{ home_kube_dir }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: create link to configuration
  ansible.builtin.file:
    src: "{{ base_kube_conf_dir }}"
    dest: "{{ home_kube_dir }}/config"
    state: link
    owner: "{{ username }}"
