- name: check if pod network exist
  ansible.builtin.shell: kubectl get namespaces calico-system 2>/dev/null
  register: network_exist
  failed_when: network_exist.rc > 1
  become: false
  become_user: "{{ username }}"

- name: Calico install
  block:
    - name: install calico network operator
      kubernetes.core.k8s:
        src: "{{network_operator}}"
        state: present
        kubeconfig: "{{ base_kube_conf_dir }}"

    - name: install  calico crd
      kubernetes.core.k8s:
        template: "{{ calico }}"
        state: present
        kubeconfig: "{{ base_kube_conf_dir }}"
  when: network_plugin == "calico"
  #  - network_exist.rc == 1
   

- name: enable metrics
  ansible.builtin.script: "{{ calico_enable_metrics }}"
  environment:
    KUBECONFIG: "{{ base_kube_conf_dir }}"

