- name: base_provision
  hosts: all
  become: true
  tasks:
  
    - name: create user
      ansible.builtin.user:
        name: "{{ username }}"
        groups: 
          - sudo
        password: "{{ password | password_hash('sha512') }}"
        shell: "{{ item.shell | default('/bin/bash') }}" 
        state: present
      
        
    - name: add ssh keys
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', '/home/vlad/.ssh/id_rsa.pub') }}"

    - name: Generate ssh key
      community.crypto.openssh_keypair:
        path: /home/{{ username }}/.ssh/id_rsa
        size: 2048
        type: ed25519
        owner: "{{ username }}"
        force: true

    - name: copy ssh pub key to autorize
      ansible.builtin.shell:
        cat /home/{{ username }}/.ssh/id_rsa.pub >> /home/{{ username }}/.ssh/authorized_keys
        

    - name: add gpg key
      ansible.builtin.apt_key:
        url: "{{ item }}"
        state: present
        validate_certs: no
      loop: "{{ gpg_keys }}"

    - name: add repo
      ansible.builtin.apt_repository:
        repo:  "{{ item }}"
        state: present
      loop: "{{ repo }}"
    
    - name: install base soft
      ansible.builtin.apt:
        name: "{{ soft }}"
        state: present
        update_cache: true

    - name: Check if trivy is installed
      command: dpkg-query -W trivy
      register: trivy_deb
      failed_when: trivy_deb.rc > 1
      changed_when: trivy_deb.rc == 1

    - name: install trivy scaner
      block:
      - name: download trivi
        ansible.builtin.uri:
          url: "{{ trivi_url }}"
          dest: /tmp/trivy.deb

      - name: install trivi from deb
        ansible.builtin.apt:
          deb: /tmp/trivy.deb
      
      - name: delete file
        ansible.builtin.file:
          path: /tmp/trivy.deb
          state: absent
      
      when: trivy_deb.rc == 1

    # - name: modify usergroup
    #   ansible.builtin.user:
    #     name: "{{ item.name }}"
    #     groups: "{{ item.groups }}"
    #     state:  present
        
    - name: Change /var/run/docker.sock permission
      ansible.builtin.file:
        path: /var/run/docker.sock
        mode: '0666'
           
        
        
        
          
