- name: use var for ubuntu
  ansible.builtin.include_vars: "{{ ansible_facts.os_family }}.yaml"

- name: install req packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true

- name: Check if {{ postgresql }} is installed
  ansible.builtin.command:
    cmd: "dpkg-query -W {{ postgresql }}"
  register: postgresql_installed
  failed_when: postgresql_installed.rc >1
  changed_when: postgresql_installed.rc == 1


- ansible.builtin.debug:
    msg: "{{ postgresql }} already install"
  when: postgresql_installed.rc == 0

- name: Install {{ postgresql }}
  block:

  - name: Add apt key for PostgreSQL
    ansible.builtin.apt_key:
      url: "{{ url_apt_key }}"
      state: present

  - name: add postgresql repo
    ansible.builtin.apt_repository:
      repo: "{{ repo }}"
      filename: pgdg
      update_cache: true

  - name: install postgresql
    ansible.builtin.apt:
      name: "{{ postgresql }}"
      state: present
      update_cache: true
  when: postgresql_installed.rc == 1
