- name: use var for ubuntu
  ansible.builtin.include_vars: "{{ ansible_facts.os_family }}.yaml"

- name: install req packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present

- name: install req python packages for role
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present

- name: Add apt key for PostgreSQL
  ansible.builtin.apt_key:
    url: "{{ url_apt_key }}"
    state: present

- name: add postgresql repo
  ansible.builtin.apt_repository:
    repo: "{{ repo }}"
    filename: pgdg
    update_cache: true

- name: install postgresql
  ansible.builtin.apt:
    name: "{{ postgresql }}"
    state: present
    update_cache: true
