---
- name: Install  collection 
  ansible.builtin.command: "ansible-galaxy collection install -r {{ role_path }}/requirements.yaml"
  become: false
  run_once: true
  delegate_to: localhost

- name: Install postgresql
  ansible.builtin.include_tasks: install-postgresql.yaml
  when: ansible_facts.os_family == "Debian"
    
- name: config postgresql
  ansible.builtin.include_tasks: config-postgresql.yaml
  
- name: add user, db and privileges
  ansible.builtin.include_tasks: create-user-db-priv.yaml

