---
- name: Install community.postgresql collection
  block:
    - name: Check if community.postgresql collection exists
      ansible.builtin.command: ansible-galaxy collection list --format json
      register: collections_check
      changed_when: false
      failed_when: false

    - name: Install community.postgresql collection if missing
      ansible.builtin.command: ansible-galaxy collection install community.postgresql
      when: "'community.postgresql' not in collections_check.stdout"
      changed_when: true
      become: false
  delegate_to: localhost

- ansible.builtin.debug:
    var: ansible_facts.os_family

- name: Install postgresql
  ansible.builtin.include_tasks: install-postgresql.yaml
  when: ansible_facts.os_family == "Debian"
    
- name: config postgresql
  ansible.builtin.include_tasks: config-postgresql.yaml
  
- name: add user, db and privileges
  ansible.builtin.include_tasks: create-user-db-priv.yaml

