- name: Check if kubelet.conf exists
  ansible.builtin.stat: 
    path: "/etc/kubernetes/kubelet.conf"
  register: kubelet_conf

- ansible.builtin.debug:
    msg: "{{ inventory_hostname  }} is already worker node"
  when: kubelet_conf.stat.exists

- name: add node to cluster
  ansible.builtin.shell: "{{  master_token }} "
  when: not kubelet_conf.stat.exists
