- name: Check if kubelet.conf exists
  ansible.builtin.stat: 
    path: "/etc/kubernetes/kubelet.conf"
  register: kubelet_conf

- ansible.builtin.debug:
    msg: "{{ inventory_hostname  }} is already worker node"
  when: kubelet_conf.stat.exists

- ansible.builtin.debug:
    var: token

- name: Add worker node {{ inventory_hostname }}
  block:
  - name: copy template kubeadm-join
    ansible.builtin.template:
      src: kubeadm-join-worker.yaml.j2
      dest: "/tmp/kubeadm-join-worker.yaml"

  - name: kubeadm init
    ansible.builtin.shell: kubeadm join --config /tmp/kubeadm-join-worker.yaml
  when: not kubelet_conf.stat.exists


