- name: base_provision
  hosts: all
  become: true
  ignore_errors: true
  tasks:

    - name: create user
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        password: "{{ item.password | password_hash('sha512') }}"
        shell: /bin/bash
        state: present
      loop: "{{ user }}"
        

    - name: add ssh keys
      authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ lookup('file', '/home/vlad/.ssh/id_rsa.pub') }}"
      loop: "{{ user }}"

    - name: update host file
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item].ansible_facts.eth1.ipv4.address }} {{hostvars[item].ansible_hostname}}"
      loop: "{{ groups.all }}"

    